apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.component_name }}
data:
  {{- range $key, $value := .Values.configmap_data }}
            {{ $key }}: {{ $value | quote | nindent 2}}
  {{- end }}


